### ISSUE TITLE
Null safety

### ISSUE THREAD

**Issue by aguilaair** [aguilaair/Companion#1]
null-safety compatible versions do not exist for:
 - [x] material_floating_search_bar -> In Progress at https://github.com/bnxm/material_floating_search_bar
 - [x] settings_ui -> Exsisting pull request at https://github.com/yako-dev/flutter-settings-ui/pull/60
 - [x] filesize -> No development for more than a year, has to be forked and developed
 - [ ] pubspec_yaml -> Seems active, filed issue https://github.com/alexei-sintotski/pubspec_yaml/issues/32
 - [ ] file_chooser ->Pull request open at https://gitlab.com/testapp-system/file_chooser/-/merge_requests/1
 - [ ] pub_api_client -> Seems active, by FVM team https://github.com/leoafarias/pub_api_client
 - [ ] fvm -> FVM team, seems active
 - [x] build_runner -> Not necessary

**Comment by simolus3** [comment]
Note that `build_runner` will probably not migrate to null-safety soon. The good news is that you don't need to actually wait for it! Since you probably don't have an `import 'package:build_runner/` in your code, you don't need that package to be migrated.

**Comment by aguilaair** [comment]
Migrated to filesize_plus with null safety support

**Comment by aguilaair** [comment]
material_floating_search_bar 0.3.0 supports null safety

**Comment by aguilaair** [comment]
settings_ui  released a pre-release
