### ISSUE TITLE
Maintainer

### ISSUE THREAD

**Issue by leoafarias** [aguilaair/Companion#5]
Hi @aguilaair I see you are doing some good work here. Seems a lot of the goals and improvements are overlapping to the roadmap that I have. If you want to contribute closely to sidekick let me know, I just opened all to maintainers on fvm.

**Comment by aguilaair** [comment]
Hey! That would definitely be an option. Could I know a little bit more about the roadmap you had planned for Sidekick?

**Comment by leoafarias** [comment]
@aguilaair Plan on focusing as the same suggested a sidekick for Flutter development. 
- Configuration management, and templates for IDE
- Suggest upgrades based on test results
- Donation support for most-used packages
- Theming support
- Null safety migration
- Automated tests

**Comment by aguilaair** [comment]
That sounds great! My only grudge would be throwing away all the time I spent mocking up the logo and graphics for Companion 🤣🤣🤣

Count me in!

Pd. Would you consider a rename? I really do feel proud of the logo and graphics 😅

**Comment by aguilaair** [comment]
If not that's completely fine too 🙃
