### ISSUE TITLE
Not able to open it in mac

### ISSUE THREAD

**Issue by tank777** [aguilaair/Companion#7]
I am not able to open it. 
Mac OS: 10.14.4

**Comment by aguilaair** [comment]
Hey! Are you building it from source or downloading a release?

**Comment by aguilaair** [comment]
Just checked on a MacOS vm, I cannot launch the app either, but no error is produced... I'll investigate further ASAP

**Comment by aguilaair** [comment]
![image](https://user-images.githubusercontent.com/29983481/111291103-1f3fb180-8647-11eb-997c-cf856629c834.png)
Could this be the issue?

**Comment by tank777** [comment]
> Hey! Are you building it from source or downloading a release?

Downloading a release

**Comment by aguilaair** [comment]
@tank777 Release  0.3.1 is working fine on MacOS, you can use it in the meantime

**Comment by aguilaair** [comment]
ad71e9922476d818c52486b1fa7dfc27642975fb This is probably the culprit

**Comment by aguilaair** [comment]
Sorry, got closed automatically.

I'm still troubleshooting.

**Comment by aguilaair** [comment]
Hey @tank777!

This will be fixed in the next version, I'll ping you again once I release it. Sorry for the inconvenience!

**Comment by tank777** [comment]
> Hey @tank777!
> 
> This will be fixed in the next version, I'll ping you again once I release it. Sorry for the inconvenience!

Yes sure, I will check the new version.  Thanks for the wonderful app.

**Comment by aguilaair** [comment]
My pleasure! Version 0.5.1+ now has the required fixes :)
